MoodleProject/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoodleProject.Models;

namespace MoodleProject.Controllers
{
    public class AdminController : Controller
    {
        private readonly MyDbContext _context;

        public AdminController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Admin
        public async Task<IActionResult> Index()
        {
              return _context.Users != null ? 
                          View(await _context.Users.ToListAsync()) :
                          Problem("Entity set 'DatabaseContext.Users'  is null.");
        }

        // GET: Admin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // GET: Admin/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,LastName,Email,Password,permisson_level")] Users users)
        {
            if (ModelState.IsValid)
            {
                _context.Add(users);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        // GET: Admin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var users = await _context.Users.FindAsync(id);
            if (users == null)
            {
                return NotFound();
            }
            return View(users);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,LastName,Email,Password,permisson_level")] Users users)
        {
            if (id != users.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(users);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsersExists(users.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(users);
        }

        // GET: Admin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var users = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (users == null)
            {
                return NotFound();
            }

            return View(users);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'DatabaseContext.Users'  is null.");
            }
            var users = await _context.Users.FindAsync(id);
            if (users != null)
            {
                _context.Users.Remove(users);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsersExists(int id)
        {
          return (_context.Users?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MoodleProject/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Build.Framework;
using Microsoft.EntityFrameworkCore;
using MoodleProject.Models;
using System.Data.Entity;
using System.Security.Policy;
using static NuGet.Packaging.PackagingConstants;


namespace MoodleProject.Controllers
{
    public class CourseController : Controller
    {
        private readonly MyDbContext _context;
        private readonly IWebHostEnvironment _env;
        public CourseController(MyDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index(int? id)
        {
            var courses = _context.Courses.FirstOrDefault(c => c.Id == id);

            return View(courses);
        }

        public IActionResult View(int? id)
        {
            var courses = _context.Courses.FirstOrDefault(c => c.Id == id);

            return View("View", courses);
        }
        [HttpPost]
        public async Task<IActionResult> AddTask(IFormCollection collection)
        {
            if (collection.Files.First() != null && collection.Files.First().Length > 0)
            {
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(collection.Files.First().FileName);
                var filePath = Path.Combine(_env.WebRootPath, "uploads", fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await collection.Files.First().CopyToAsync(fileStream);
                }
                var task = new Tasks()
                {
                    Name = collection["taskName"],
                    Description = collection["taskDescription"],
                    End_Date = collection["taskEndDate"],
                    File_Path = filePath,
                    Url = collection["taskUrl"],
                    Holder_id = int.Parse(collection["holderId"]),                    
                };
                _context.Tasks.Add(task);
                _context.SaveChanges();
                return View("Index",_context.Holders.FirstOrDefault(x => x.Id == task.Holder_id).Course);
            }
            return View();
        }

        [HttpPost]
        public ActionResult AddHolder(IFormCollection collection)
        {
            var holder = new Holders()
            {
                Name = collection["holderNameInput"],
                Id_Course = int.Parse(collection["course_Id"]),
                CourseId = int.Parse(collection["course_Id"]),
                Tasks = new List<Tasks>()
            };
            _context.Holders.Add(holder);
            _context.SaveChanges();
            return View("Index", _context.Courses.FirstOrDefault(c => c.Id == holder.Id_Course));
        }

        public ActionResult Courses()
        {
            Users currentUser= _context.Users.Find(int.Parse(Request.Cookies["UserId"]));
            var courses = _context.Courses
            .Where(c => c.Id_User_Teacher == currentUser.Id)
            .ToList();

            return View(courses);
        }
    }
}

MoodleProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@inject MyDbContext DbContext


@{
    string userId = HttpContextAccessor.HttpContext.Request.Cookies["UserId"];
    Users user = new Users();
    List<Courses> courses = new List<Courses>();
    if (userId != null)
    {
        user = DbContext.Users.FirstOrDefault(u => u.Id == int.Parse(userId));
        int[] _courses = DbContext.UsersCourses.Where(u => u.Id_User == int.Parse(userId)).Select(u => u.Id_Course).ToArray();
        foreach (var item in _courses)
        {
            Courses course = DbContext.Courses.FirstOrDefault(u => u.Id == item);
            courses.Add(course);
        }
    }
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoodleProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoodleProject.styles.css" asp-append-version="true" />
</head>
<body>

    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3  border-bottom">
        <div class="col-md-3 mb-2 mb-md-0">
            <a class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none mx-5 fs-4 text-dark">
                Освітній портал
            </a>
        </div>                                                      
        
        @if (userId == null)
        {
            <div class="col-md-3 text-end mx-5">
                <a type="button" class="btn btn-outline-primary me-2" asp-action="Login" asp-controller="User">Login</a>
            </div>
        }
        else
        {
            <div class="dropdown text-end mx-5">
                <a class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    @user.Name @user.LastName
                </a>
                <ul class="dropdown-menu text-small" style="">
                    <li><a class="dropdown-item" asp-action="Profile" asp-controller="User">Profile</a></li>
                    @if (user.permisson_level == 2)
                    {
                        <li><a class="dropdown-item" asp-action="Index" asp-controller="Admin">Admin</a></li>
                    }
                    @if (user.permisson_level == 1)
                    {
                        <li><a class="dropdown-item" asp-action="Courses" asp-controller="Course">Teacher</a></li>
                    }
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-action="Logout" asp-controller="User">Sign out</a></li>
                </ul>
            </div>
        }
        
        
    </header>
    
    
    
    <div class="row align-items-center">
        <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-body-tertiary col-1" style="width: 200px;">
            <div class="list-group list-group-flush scrollarea">
                @foreach (var item in courses)
                {
                    <a asp-route-id="@item.Id" asp-controller="Course" asp-action="view" class="list-group-item list-group-item-action py-3 lh-sm" aria-current="true">
                        <div class="d-flex w-100 align-items-center justify-content-between">
                            <strong class="mb-1">@item.Name</strong>>
                        </div>
                    </a>
                }
            </div>
        </div>
        <div class="container">
            <main role="main" class="pb-3 col-15">
                @RenderBody()
            </main>
        </div>
    </div>

    
    <footer class="py-3 my-4 border-top">
        <p class="text-center text-muted">©Profesional Bradley 2023 Company, Inc</p>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>